% test program
clc; close all; clear ll
Fs = 8000;
[x Fs]=audioread('one.wav');  
d1=melfunction(x);
[x Fs]=audioread('two.wav');  
d2=melfunction(x);
[x Fs]=audioread('three.wav');  
d3=melfunction(x);
[x Fs]=audioread('four.wav');  
d4=melfunction(x);
[x Fs]=audioread('five.wav');  
d5=melfunction(x);
[x Fs]=audioread('six.wav');  
d6=melfunction(x);
[x Fs]=audioread('seven.wav');  
d7=melfunction(x);
[x Fs]=audioread('eight.wav');  
d8=melfunction(x);
[x Fs]=audioread('nine.wav');  
d9=melfunction(x);
[x Fs]=audioread('ten.wav');  
d10=melfunction(x);
[x Fs]=audioread('one1.wav');  
d11=melfunction(x);
[x Fs]=audioread('two1.wav');  
d21=melfunction(x);
[x Fs]=audioread('three1.wav');  
d31=melfunction(x);
[x Fs]=audioread('four1.wav');  
d41=melfunction(x);
[x Fs]=audioread('five1.wav');  
d51=melfunction(x);
[x Fs]=audioread('six1.wav');  
d61=melfunction(x);
[x Fs]=audioread('seven1.wav');  
d71=melfunction(x);
[x Fs]=audioread('eight1.wav');  
d81=melfunction(x);
[x Fs]=audioread('nine1.wav');  
d91=melfunction(x);
[x Fs]=audioread('ten1.wav');  
d101=melfunction(x);
[x Fs]=audioread('one2.wav');  
d12=melfunction(x);
[x Fs]=audioread('two2.wav');  
d22=melfunction(x);
[x Fs]=audioread('three2.wav');  
d32=melfunction(x);
[x Fs]=audioread('four2.wav');  
d42=melfunction(x);
[x Fs]=audioread('five2.wav');  
d52=melfunction(x);
[x Fs]=audioread('six2.wav');  
d62=melfunction(x);
[x Fs]=audioread('seven2.wav');  
d72=melfunction(x);
[x Fs]=audioread('eight2.wav');  
d82=melfunction(x);
[x Fs]=audioread('nine2.wav');  
d92=melfunction(x);
[x Fs]=audioread('ten2.wav');  
d102=melfunction(x);
tr =[d1; d2; d3; d4; d5; d6; d7; d8; d9; d10;d11; d21; d31; d41; d51; d61; d71; d81; d91; d101;d12; d22; d32; d42; d52; d62; d72; d82; d92; d102]; % training features
y_tr= [1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10];  % tranining class
[x Fs]=audioread('testone.wav');
testvoice1=melfunction(x);
test_data=[testvoice1]; % test features
y_test=[1]'; % test class
[y err]=knn(test_data,y_test, tr, y_tr, 3)
